name: deploy-test

on:
  pull_request:
    branches: 
      - master

jobs:
  deploy-test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Setup Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - name: Serverless deployment
      uses: serverless/github-action@v1.49.0
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLS_DEBUG: "*"
    - name: Deploy every service
      run: |
        cd services
        sudo ./deploy_every_service.sh test
    - name: Integration tests
      run: |
        cd services/integration_tests
        sudo ./install_integration_reqs.sh
        -python -m pytest
